version: "3.5"

services:
  backend:
    build: ./backend
    image: pop/backend
    volumes:
      - ./backend:/root
    ports:
      - 3333:3333
      - 9229:9229
    command: bash -c "yarn dev"
  frontend:
    build: ./frontend
    image: pop/frontend
    # volumes:
    #   - ./frontend:/root
    ports:
      - 8080:8080
    # command: bash -c "yarn dev"
