version: "3.5"

services:
  backend:
    build: ./backend
    image: pop/backend
    volumes:
      - ./backend:/root
    ports:
      - 3333:3333
      - 9229:9229
    command: bash -c "yarn dev"

  frontend:
    build: ./frontend
    image: pop/frontend
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - ./frontend:/root
    ports:
      - 3000:3000
    command: bash -c "yarn install && yarn start"
